### ISSUE TITLE
Visual

### ISSUE THREAD

**Issue by ercknard** [MarcKianPrincipe/MPTII-Master_Assets#1]
any visual of this?

**Comment by MarcKianPrincipe** [comment]
![Summary](https://github.com/MarcKianPrincipe/MPTII-Master_Assets/assets/122709222/a7b25a22-068e-414a-80c4-1d9404f4caf6)
![User](https://github.com/MarcKianPrincipe/MPTII-Master_Assets/assets/122709222/f05c3897-3197-4190-87fd-5be2680fe2f1)
![Login](https://github.com/MarcKianPrincipe/MPTII-Master_Assets/assets/122709222/81c5f354-1567-4a6e-b590-b3074799740c)
![Admin](https://github.com/MarcKianPrincipe/MPTII-Master_Assets/assets/122709222/6bf649e8-0140-4fdc-95fa-bbf623db6acb)
